SELECT *
FROM {{ ref('fct_contract_health') }}
WHERE contract_risk_score NOT IN ('CHURN_RISK', 'MIXED_ENGAGEMENT_DECLINING', 'STAGNANT', 'UPSELL_OPPORTUNITY', 'MONITOR', 'USAGE_DATA_UNAVAILABLE', 'UNABLE_TO_DETERMINE')
